### ISSUE TITLE
How to successfully boot into the Force OS

### ISSUE THREAD

**Issue by bonsaipanda** [TheKikGen/MPC-LiveXplore-bootstrap#2]
Just checking the boxes on what are the prerequisites and steps to actually boot into the Force OS from the chroot image?

I wrote the image to an SD card, put it in the MPC (Live 1) slot and powered it up but it booted into the normal MPC OS. I have the latest SSH image installed on the MPC, but I seem to be missing a step here.

**Comment by TheKikGen** [comment]
do you have any other key plugged in ?  Or a tkgl_bootstrap dir ?
I'm correcting some issues currently, to make this mod less preliminary !
You can test it manually, step by if you look at the tkgl_iamforce.sh script.
in a ssh session, cd to  /media/TKGL_BOOTSTRAP/media/tkgl_bootstrap_[ProjectData]/scripts  
and run tkgl_bootstrap : # sh ./tkgl_bootstrap

You can also have a look at the logs  /media/TKGL_BOOTSTRAP/media/tkgl_bootstrap_[ProjectData]/logs

**Comment by bonsaipanda** [comment]
Ah, that was the key that was missing - I have none of the bootstrap stuff as I thought it was bundled within the image itself. I'll have to dive into that first.

**Comment by TheKikGen** [comment]
In deed.  my goal is to use an original unmodified image, and to be less intrusive as possible...
