### ISSUE TITLE
I just wondering

### ISSUE THREAD

**Issue by ShoveD01** [TheKikGen/MPC-LiveXplore-bootstrap#5]
I'm having a problem where the main button on my Mpc one has suddenly stopped working, the switch itself appears to be ok.
So I was wondering if a hidden "mapping" file could have got corrupt, have you come across such a file in your good work.

**Comment by TheKikGen** [comment]
It stopped with the original Akai firmware ?

**Comment by ShoveD01** [comment]
Yes it is the original akai firmware

**Comment by TheKikGen** [comment]
So it is a harware problem... This button sends midi event.
What you can do is to install and ssh firmware, connect to your MPC, and use **amidi** to dump received messages when you turn / press the main encoder.

**Comment by ShoveD01** [comment]
Brilliant , using ssh was gonna be my next step , so if these buttons are just sending midi to the software, I guess they have to be mapped somewhere, would that be correct.?
