### ISSUE TITLE
RTP Midi, Troubles getting started

### ISSUE THREAD

**Issue by alexgustafson** [TheKikGen/MPC-LiveXplore-bootstrap#6]
I am having trouble getting rtp midi running on my MPC Live.

I updated the MPC system using the ssh update images.
I have started with the Simple bootstrap image from a usb stick. It contains the tkgl_bootstrap[ProjectData] directory. 
I have modified the TKGL_DOER parameter at the bottomg of the dort_list file to include rtpmidid and nomoreazmidi.

If I include the playlogo module in the list, I see the logo animation playing on startup. If I dont include it, I dont see the animation. So that is indicating that things are working in general.

From my computer, if I run ```avahi-browse --all```  then I see:

```wlp113s0 IPv4 B0-F1-EC-FF-9B-74-0001-MPC-Live--             _inmusic-device._tcp local```

and nothing indicating that rtp midi is running.

How could I check if there are any errors starting the rtp midi service. Am I missing some step?

**Comment by TheKikGen** [comment]
Hi. Do you see any new midi port within your MPC ?
