### ISSUE TITLE
rtpmidid unsupported overlay

### ISSUE THREAD

**Issue by ghost** [TheKikGen/MPC-LiveXplore-bootstrap#7]
I seem to have mounted the bootstrap image successfully, however rtpmidi never actually seems to be active, other modules load fine, play logo etc. It looks like something to do with the overlay as far as I can tell?

Device: MPC One
Firmware: 2.11.2

Here is some log info:

`Jul 26 01:24:12 mpc-one kernel: overlayfs: filesystem on '/media/TKGL/tkgl_bootstrap_[ProjectData]/modules/mod_rtpmidid/etc/overlay' not supported
Jul 26 01:24:12 mpc-one az01-launch-MPC[986]: mount: /etc: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
Jul 26 01:24:12 mpc-one az01-launch-MPC[987]: avahi:x:1011:1011:Avahi mDNS daemon:/var/run/avahi-daemon:/bin/false
Jul 26 01:24:12 mpc-one az01-launch-MPC[988]: avahi:x:1011:avahi
Jul 26 01:24:12 mpc-one az01-launch-MPC[989]: Failed to open file '/etc/avahi/avahi-daemon.conf': No such file or directory`

Any ideas what's happening here?

**Comment by TheKikGen** [comment]
Hmmm,  I tested that on an MPC and a Force.  Overlay are used with internal smartcard.
I'm not sure the directory structure is the same....It is probably why the overlay can't be mounted.

Check the module source here : https://github.com/TheKikGen/MPC-LiveXplore-bootstrap/blob/main/tkgl_bootstrap_%5BProjectData%5D/modules/mod_rtpmidid/tkgl_mod_rtpmidid.sh

Try to mount the overlay manually first, and post the result here.
